const Cardsdata = [
    {
        id: 1,
        dish: "Punjabi",
        imgData: "https://th.bing.com/th/id/OIP.AkpCOIE4zoJyfRNPjHPgfwHaHa?w=191&h=191&c=7&r=0&o=5&pid=1.7",
        address: "North Indiad, biryani",
        somedata: "1175 + order placed from here resently",
        price: 350,
        rating: "3.8",
        arrimg: "",
        qnty: 0,
    },
    {
        id: 2,
        dish: "Juggadi adda",
        imgData: "https://th.bing.com/th/id/OIP.GGr3TR8xnCBuiT1rFM8mygHaFj?w=226&h=180&c=7&r=0&o=5&pid=1.7",
        address: "Street food",
        somedata: "2525 + order placed from here resently",
        price: 25,
        rating: "3.9",
        arrimg: "",
        qnty: 0,
    },
    {
        id: 3,
        dish: "La milano",
        imgData: "https://th.bing.com/th/id/OIP.bpTjPj8xV2o5bYYaSxClsAHaDk?w=331&h=168&c=7&r=0&o=5&pid=1.7",
        address: "Pizza, fast food, pasta",
        somedata: "650 + order placed from here resently",
        price: 70,
        rating: "4.2",
        arrimg: "",
        qnty: 0,
    },
    {
        id: 4,
        dish: "Momoman",
        imgData: "https://th.bing.com/th/id/OIP.iBgRh5jBfeB4L9u0jdrOWQHaE8?w=255&h=180&c=7&r=0&o=5&pid=1.7",
        address: "North Indiad, biryani",
        somedata: "300 + order placed from here resently",
        price: 70,
        rating: "3.8",
        arrimg: "",
        qnty: 0,
    },
    {
        id: 5,
        dish: "Jassi de",
        imgData: "https://th.bing.com/th/id/OIP.l-UqZA41ADhGaU5VbGY2FgHaHZ?w=174&h=180&c=7&r=0&o=5&pid=1.7",
        address: "North Indiad, biryani",
        somedata: "1050 + order placed from here resently",
        price: 210,
        rating: "4.0",
        arrimg: "",
        qnty: 0,
    },
    {
        id: 6,
        dish: "Hocco eatery",
        imgData: "https://th.bing.com/th/id/OIP.GjIwCh89aXCNSbCMbriWkwHaE7?w=260&h=180&c=7&r=0&o=5&pid=1.7",
        address: "North Indiad, biryani",
        somedata: "500 + order placed from here resently",
        price: 300,
        rating: "3.8",
        arrimg: "",
        qnty: 0,
    },
    {
        id: 7,
        dish: "Hocco eatery",
        imgData: "https://th.bing.com/th/id/OIP.GjIwCh89aXCNSbCMbriWkwHaE7?w=260&h=180&c=7&r=0&o=5&pid=1.7",
        address: "North Indiad, biryani",
        somedata: "500 + order placed from here resently",
        price: 300,
        rating: "3.8",
        arrimg: "",
        qnty: 0,
    },
    {
        id: 8,
        dish: "Hocco eatery",
        imgData: "https://th.bing.com/th/id/OIP.GjIwCh89aXCNSbCMbriWkwHaE7?w=260&h=180&c=7&r=0&o=5&pid=1.7",
        address: "North Indiad, biryani",
        somedata: "500 + order placed from here resently",
        price: 300,
        rating: "3.8",
        arrimg: "",
        qnty: 0,
    },
]

export default Cardsdata;